name: Bienvenida!

on:
  push:
    branches:
      - master

jobs:
  saludo_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Saludar
        run: |
          echo "Hola Github Actions!!!"
      - name: date
        run: date - print or set the system date and time
